<?xsl version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:fo="http://www.w3.org/1999/XSL/Format">

	<xsl:template macth="/">
		<xsl:call-template name="rml" />
	</xsl:template>
        
	<xsl:template name="rml">
		<document filename="example.pdf">
			<template pageSize="29cm,21cm" leftMargin="2.0cm" rightMargin="2.0cm" topMargin="2.0cm" bottomMargin="2.0" title="Test" author="Generated by OpenERP Fabien Pinckaers" allowSplitting="20">
			</template>
		</document>
	</xsl:template>
</xsl:stylesheet>
